### PR TITLE
added --prune flag for push command

### PR DESCRIPTION
**Pull request by TanguyAndreani**
Allows to remove files that are on the remote server but not in the
local directory.

Related issue: #25

### CODE REVIEW

**Comment by TanguyAndreani** [comment]
I stashed my commits into one for clarity

**Comment by TanguyAndreani** [comment]
For consistency, I probably shouldn’t use display_response

**Comment by TanguyAndreani** [comment]
I could just add a dry run parameter to the `delete` API call or make `-prune` and `-dry-run` mutually exclusive. Which one is better?

**Comment by TanguyAndreani** [comment]
I'm done with it, unless someone wants me to change things.

**Comment by kyledrake** [comment]
Apologies for the really long delay here, thanks for this! I'll merge it now.

**Pull request merged**
